# Generated by Django 3.1.6 on 2021-02-05 11:24

from django.db import migrations
from django.db.models import Sum


def add_most_popular_item(apps, schema_editor):
    Trade = apps.get_model('trades', 'Trade')
    Inventory = apps.get_model('trades', 'Inventory')
    User = apps.get_model('auth', 'User')
    item = Trade.objects.filter().annotate(sum=Sum('quantity')).order_by('-sum').first().item
    if item:
        for user in User.objects.all():
            try:
                inventory = Inventory.objects.get(user__id=user.id, item=item)
                inventory.quantity = inventory.quantity + 1
                inventory.save(update_fields=('quantity',))
            except Inventory.DoesNotExist:
                Inventory(user=user, quantity=1, item=item).save()


class Migration(migrations.Migration):
    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_most_popular_item),
    ]
