version: "3.7"

services:
  db:
    image: postgres
    ports:
      - 5434:5432
    env_file:
      trade_app/.env
  web:
    build:
      context: trade_app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      trade_app/.env