version: "3.7"

services:
  db:
    image: postgres
    ports:
      - 5434:5432
    env_file:
      trade_app/.env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
  web:
    build:
      context: trade_app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      trade_app/.env
  redis:
    image: redis:alpine
    ports:
      - 6380:6379
    volumes:
      - ./trades_app-redis:/data
  celery:
    build:
      context: trade_app
      dockerfile: Dockerfile
    command: celery -A trade_app worker -B
    env_file: trade_app/.env
    depends_on:
      - redis
      - web
    volumes:
      - ./trade_app/:/app